### PR TITLE
fix(file-dropzone): wcag fixes #54

### LINKED ISSUE #54: [FileDropzone]: WCAG react issues
## Problem
9.1.3.1 - Valitud failide sulgemisel ei saa aru, mida sulgetakse, sest ütleb ainult nupu nime.
9.2.1.1 - Disabled komponent ei ole päriselt disabled.
9.4.1.2 - Ei uuendata dropzone stataust: alati ütleb, et no file chosen.
9.4.1.3 - Ei loeta ette elemente, mida valitud on.

### PR DESCRIPTION
**Pull request by airikej**

### CODE REVIEW

File: src/tedi/components/form/file-dropzone/file-dropzone.tsx [hunk 1]
```diff
@@ -78,36 +87,46 @@ export const FileDropzone = (props: FileDropzoneProps): JSX.Element => {
...
-                    {file.isValid === false && <Icon name="info" color="danger" display="inline" size={18} />}
-                  </Col>
-                  <Col width="auto">
-                    <ClosingButton title={getLabel('clear')} onClick={() => onFileRemove(file)} />
-                  </Col>
-                </Row>
-              </CardContent>
-            </Card>
+                <CardContent
+                  padding={{
```
Comment (mart-sessman) [inline src/tedi/components/form/file-dropzone/file-dropzone.tsx]: could just use single number value instead of object which defines same value for every field
